package kirimbatikoop;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormBatik extends javax.swing.JFrame {
    
    DefaultTableModel mdl = new DefaultTableModel();
    String PrimaryKey;
    String MainDatabase = "internal";
    String DbsTable = "orders";

    public FormBatik() {
        initComponents();
        tampil_tabel_dbase();
        btn_saveedit.setVisible(false);
        btn_cancel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        no_kirim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nama_pembeli = new javax.swing.JTextField();
        tanggal_kirim = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        kode_batik = new javax.swing.JComboBox();
        harga_perkode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tarif_satu = new javax.swing.JTextField();
        tarif_dua = new javax.swing.JTextField();
        tarif_tiga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        motif_batik = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jumlah_kodi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        harga_total = new javax.swing.JTextField();
        biaya_kirim = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        prs_ya = new javax.swing.JRadioButton();
        prs_tidak = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        prs_persen = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        biaya_admin = new javax.swing.JTextField();
        total_biaya = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_hitung = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_form = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btn_simpan = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_saveedit = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("No. Kirim");

        jLabel2.setText("Nama Pembeli");

        jLabel3.setText("Tanggal Kirim");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nama_pembeli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addComponent(no_kirim, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(tanggal_kirim, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(no_kirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama_pembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanggal_kirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Motif Batik");

        kode_batik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "BTK-01", "BTK-02", "BTK-03", "BTK-04" }));
        kode_batik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_batikActionPerformed(evt);
            }
        });

        jLabel5.setText("Kode Batik");

        jLabel6.setText("Harga Per-Kode");

        jLabel7.setText("Tarif 1 (1-5 Kodi)");

        jLabel8.setText("Tarif 2 (6-15 Kodi)");

        jLabel9.setText("Tarif 3 (>15 Kodi)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kode_batik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(motif_batik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(harga_perkode, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tarif_tiga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(tarif_dua, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tarif_satu, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kode_batik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(motif_batik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harga_perkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarif_satu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarif_dua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarif_tiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jumlah_kodi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlah_kodiKeyReleased(evt);
            }
        });

        jLabel10.setText("Jumlah Kodi");

        jLabel11.setText("Total Harga");

        jLabel12.setText("Biaya Kirim");

        prs_ya.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(prs_ya);
        prs_ya.setText("Ya");
        prs_ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prs_yaActionPerformed(evt);
            }
        });

        prs_tidak.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(prs_tidak);
        prs_tidak.setSelected(true);
        prs_tidak.setText("Tidak");
        prs_tidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prs_tidakActionPerformed(evt);
            }
        });

        jLabel13.setText("Prosentase");

        prs_persen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "5", "10", "15" }));
        prs_persen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prs_persenActionPerformed(evt);
            }
        });

        jLabel14.setText("%");

        jLabel15.setText("Biaya Administrasi");

        jLabel16.setText("Total Biaya");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga_total, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlah_kodi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(total_biaya, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(biaya_kirim)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prs_tidak)
                                    .addComponent(prs_ya))
                                .addGap(18, 18, 18)
                                .addComponent(prs_persen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addComponent(biaya_admin))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah_kodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harga_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biaya_kirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prs_ya)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prs_tidak))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prs_persen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biaya_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btn_hitung.setText("Hitung");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_hitung, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        tabel_form.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel_form);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btn_simpan.setText("Simpan dan Isi Lagi");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_saveedit.setText("Simpan Perubahan");
        btn_saveedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveeditActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_saveedit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_saveedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampil_tabel(){
        Object[] kolomz = {
            "No Kirim",
            "Nama Pembeli",
            "Tanggal",
            "Jenis Batik",
            "Jumlah Kodi",
            "Total Harga",
            "Biaya Kirim",
            "Biaya Admin",
            "Total"
        };
        mdl.setColumnIdentifiers(kolomz);
        tabel_form.setModel(mdl);
    }

    private void tampil_tabel_dbase(){
        DefaultTableModel mdlz = new DefaultTableModel();
        mdlz.addColumn("No Kirim");
        mdlz.addColumn("Nama Pembeli");
        mdlz.addColumn("Tanggal");
        mdlz.addColumn("Jenis Batik");
        mdlz.addColumn("Jumlah Kodi");
        mdlz.addColumn("Total Harga");
        mdlz.addColumn("Biaya Kirim");
        mdlz.addColumn("Biaya Admin");
        mdlz.addColumn("Total");
        try {
            String sql = "SELECT * FROM " + DbsTable;
            java.sql.Connection conn = ConnectTools.connect(MainDatabase);
            java.sql.ResultSet rs = conn.createStatement().executeQuery(sql);
            while (rs.next()) {
                String[] dataField = {
                    rs.getString("no_kirim"),
                    rs.getString("nama"),
                    rs.getString("tanggal"),
                    rs.getString("jenis_batik"),
                    rs.getString("kodi"),
                    rs.getString("harga"),
                    rs.getString("kirim"),
                    rs.getString("admin"),
                    rs.getString("total")
                };
                mdlz.addRow(dataField);
            }
            tabel_form.setModel(mdlz);
            tabel_form.setRowSelectionInterval(0, 0);
        } catch (Exception e) {}
    }

    private void isi_tabel_dbase(){
        String eSQieL = "INSERT INTO " + DbsTable + " VALUES ('" +
                no_kirim.getText().toString() + "','" +
                nama_pembeli.getText().toString() + "','" +
                tanggal_kirim.getText().toString() + "','" +
                motif_batik.getText().toString() + "','" +
                jumlah_kodi.getText().toString() + "','" +
                harga_total.getText().toString() + "','" +
                biaya_kirim.getText().toString() + "','" +
                biaya_admin.getText().toString() + "','" +
                total_biaya.getText().toString() + "')";
        try{
            java.sql.Connection conz = ConnectTools.connect(MainDatabase);
            java.sql.PreparedStatement pst = conz.prepareStatement(eSQieL);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Ditambahkan");
        } catch (Exception e){JOptionPane.showMessageDialog(null,"Data Gagal Diinput"+e.getMessage());}
    }

    private void isi_form(int row){
        PrimaryKey = tabel_form.getModel().getValueAt(row,0).toString();
        
        no_kirim.setText(tabel_form.getModel().getValueAt(row,0).toString());
        nama_pembeli.setText(tabel_form.getModel().getValueAt(row,1).toString());
        tanggal_kirim.setText(tabel_form.getModel().getValueAt(row,2).toString());
        jumlah_kodi.setText(tabel_form.getModel().getValueAt(row,4).toString());
        
        int kode = 0;
        String jenisbatik = tabel_form.getModel().getValueAt(row,3).toString();
        if(jenisbatik.equals("Kawung"))kode = 1;
        if(jenisbatik.equals("Parang"))kode = 2;
        if(jenisbatik.equals("Truntum"))kode = 3;
        if(jenisbatik.equals("Sido Mukti"))kode = 4;
        kode_batik.setSelectedIndex(kode);
        
        int admin = Integer.parseInt(tabel_form.getModel().getValueAt(row,7).toString());
        int harga = Integer.parseInt(harga_total.getText().toString());
        int persen = 100*admin/harga;
        int index = 0;
        if(persen == 5)index = 1;
        if(persen == 10)index = 2;
        if(persen == 15)index = 3;
        prs_persen.setSelectedIndex(index);
        
        biaya_admin.setText(tabel_form.getModel().getValueAt(row,7).toString());
        total_biaya.setText(tabel_form.getModel().getValueAt(row,8).toString());
    }

    private void edit_tabel(){
        String sqlEdit = "UPDATE " + DbsTable + " SET " +
                "no_kirim='" + no_kirim.getText().toString() + "', " +
                "nama='" + nama_pembeli.getText().toString() + "', " +
                "tanggal='" + tanggal_kirim.getText().toString() + "', " +
                "jenis_batik='" + motif_batik.getText().toString() + "', " +
                "kodi='" + jumlah_kodi.getText().toString() + "', " +
                "harga='" + harga_total.getText().toString() + "', " +
                "kirim='" + biaya_kirim.getText().toString() + "', " +
                "admin='" + biaya_admin.getText().toString() + "', " +
                "total='" + total_biaya.getText().toString() + "' " +
                "WHERE no_kirim='" + PrimaryKey + "'";
        try{
            java.sql.Connection conz = ConnectTools.connect(MainDatabase);
            java.sql.PreparedStatement pst = conz.prepareStatement(sqlEdit);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data Berhasil Diubah");
        } catch (Exception e){JOptionPane.showMessageDialog(null,"Data Gagal Diubah"+e.getMessage());}
    }

    private void isi_tabel(){
        Object[] rowz = new Object[9];
        rowz[0] = no_kirim.getText().toString();
        rowz[1] = nama_pembeli.getText().toString();
        rowz[2] = tanggal_kirim.getText().toString();
        rowz[3] = motif_batik.getText().toString();
        rowz[4] = jumlah_kodi.getText().toString();
        rowz[5] = harga_total.getText().toString();
        rowz[6] = biaya_kirim.getText().toString();
        rowz[7] = biaya_admin.getText().toString();
        rowz[8] = total_biaya.getText().toString();
        mdl.addRow(rowz);
    }

    private void hitung_kodi(){
        String jumlahkodi = jumlah_kodi.getText().toString();
        int totals;
        int jmlkode = 0;
        if(jumlahkodi.equals("")){jmlkode = 0;
        }else jmlkode = Integer.parseInt(jumlahkodi);
        totals = Integer.parseInt(harga_perkode.getText().toString()) * jmlkode;
        String hgt = Integer.toString(totals);
        
        harga_total.setText(hgt);
        
        int trf01 = Integer.parseInt(tarif_satu.getText().toString());
        int trf02 = Integer.parseInt(tarif_dua.getText().toString());
        int trf03 = Integer.parseInt(tarif_tiga.getText().toString());
        
        int bykirim = 0;
        if(jmlkode>=1&&jmlkode<=5)bykirim = jmlkode * trf01;
        if(jmlkode>=6&&jmlkode<=15)bykirim = jmlkode * trf02;
        if(jmlkode>15)bykirim = jmlkode * trf03;
        
        biaya_admin.setText("");
        total_biaya.setText("");
        biaya_kirim.setText(Integer.toString(bykirim));
    }

    private void ClearInputs(){
        no_kirim.setText(null);
        nama_pembeli.setText(null);
        tanggal_kirim.setText(null);
        jumlah_kodi.setText(null);
        harga_total.setText(null);
        biaya_kirim.setText(null);
        biaya_admin.setText(null);
        total_biaya.setText(null);
        kode_batik.setSelectedIndex(0);
        prs_persen.setSelectedIndex(0);
    }

    private void kode_batikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_batikActionPerformed
        // TODO add your handling code here:
        String motif = null;
        String harga = null;
        String t1 = null;
        String t2 = null;
        String t3 = null;
        String v = kode_batik.getSelectedItem().toString();
        
        if(v.equals(" ")){
            motif_batik.setText(null);
            harga_perkode.setText(null);
            tarif_satu.setText(null);
            tarif_dua.setText(null);
            tarif_tiga.setText(null);
            harga_total.setText(null);
            biaya_kirim.setText(null);
            return;
        }else if(v.equals("BTK-01")){
            motif = "Kawung";
            harga = "400000";
            t1 = "15000";
            t2 = "7500";
            t3 = "5000";
        }else if(v.equals("BTK-02")){
            motif = "Parang";
            harga = "450000";
            t1 = "20000";
            t2 = "10000";
            t3 = "7500";
        }else if(v.equals("BTK-03")){
            motif = "Truntum";
            harga = "500000";
            t1 = "23000";
            t2 = "12000";
            t3 = "8000";
        }else if(v.equals("BTK-04")){
            motif = "Sido Mukti";
            harga = "550000";
            t1 = "17500";
            t2 = "8000";
            t3 = "6000";
        }
        motif_batik.setText(motif);
        harga_perkode.setText(harga);
        tarif_satu.setText(t1);
        tarif_dua.setText(t2);
        tarif_tiga.setText(t3);
        
        hitung_kodi();
    }//GEN-LAST:event_kode_batikActionPerformed

    private void jumlah_kodiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah_kodiKeyReleased
        // TODO add your handling code here:
        if(kode_batik.getSelectedIndex()==0){
            harga_total.setText(null);
            biaya_kirim.setText(null);
            return;
        }
        
        hitung_kodi();
        
        biaya_admin.setText(null);
        total_biaya.setText(null);
    }//GEN-LAST:event_jumlah_kodiKeyReleased

    private void prs_persenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prs_persenActionPerformed
        // TODO add your handling code here:
        if(prs_persen.getSelectedIndex()==0)prs_tidak.setSelected(true);
        else prs_ya.setSelected(true);
        biaya_admin.setText(null);
        total_biaya.setText(null);
    }//GEN-LAST:event_prs_persenActionPerformed

    private void prs_tidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prs_tidakActionPerformed
        // TODO add your handling code here:
        prs_persen.setSelectedIndex(0);
        biaya_admin.setText(null);
        total_biaya.setText(null);
    }//GEN-LAST:event_prs_tidakActionPerformed

    private void prs_yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prs_yaActionPerformed
        // TODO add your handling code here:
        prs_persen.setSelectedIndex(1);
        biaya_admin.setText(null);
        total_biaya.setText(null);
    }//GEN-LAST:event_prs_yaActionPerformed

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        if(kode_batik.getSelectedItem().equals(" ")){
            JOptionPane.showMessageDialog(null, "Kode Batik Belum Dipilih");
            return;
        }
        
        if(jumlah_kodi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Jumlah Kodi Belum Dimasukkan");
            return;
        }
        
        int pesen = Integer.parseInt(prs_persen.getSelectedItem().toString());
        int t_harga = Integer.parseInt(harga_total.getText().toString());
        int admin = pesen * t_harga / 100;
        int totals = t_harga + admin + Integer.parseInt(biaya_kirim.getText().toString());
        
        biaya_admin.setText(Integer.toString(admin));
        total_biaya.setText(Integer.toString(totals));
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        if(no_kirim.getText().equals("") || nama_pembeli.getText().equals("") || tanggal_kirim.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data yang Diisi Belum Lengkap");
            return;
        }
        
        if(total_biaya.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Hitung Total Biaya Terlebih Dahulu");
            return;
        }
        
        isi_tabel_dbase();
        ClearInputs();
        tampil_tabel_dbase();
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        btn_simpan.setVisible(false);
        btn_edit.setVisible(false);
        btn_delete.setVisible(false);
        btn_saveedit.setVisible(true);
        btn_cancel.setVisible(true);
        
        isi_form(tabel_form.getSelectedRow());
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        ClearInputs();
        btn_saveedit.setVisible(false);
        btn_cancel.setVisible(false);
        btn_simpan.setVisible(true);
        btn_edit.setVisible(true);
        btn_delete.setVisible(true);
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_saveeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveeditActionPerformed
        // TODO add your handling code here:
        if(no_kirim.getText().equals("") || nama_pembeli.getText().equals("") || tanggal_kirim.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data yang Diisi Belum Lengkap");
            return;
        }
        if(total_biaya.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Hitung Total Biaya Terlebih Dahulu");
            return;
        }
        int PilihanEdit = JOptionPane.showConfirmDialog(null, "Simpan Perubahan Pada Data?", null, JOptionPane.YES_NO_OPTION);
        if(PilihanEdit == JOptionPane.YES_OPTION){
            btn_saveedit.setVisible(false);
            btn_cancel.setVisible(false);
            btn_simpan.setVisible(true);
            btn_edit.setVisible(true);
            btn_delete.setVisible(true);
            edit_tabel();
            ClearInputs();
            tampil_tabel_dbase();
        }else{
            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_btn_saveeditActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // TODO add your handling code here:
        FormLogin flog = new FormLogin();
        flog.setVisible(true);
        flog.setTitle("Login Aplikasi");
        this.setVisible(false);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tabel_form.getSelectedRow();
        PrimaryKey = tabel_form.getModel().getValueAt(baris,0).toString();
        String sqlDelete = "DELETE FROM " + DbsTable + " WHERE no_kirim='" + PrimaryKey + "'";
        int PilihanDelete = JOptionPane.showConfirmDialog(null, "Hapus Data yang Sudah Tersimpan?", null, JOptionPane.YES_NO_OPTION);
        if(PilihanDelete == JOptionPane.YES_OPTION){
            try{
                java.sql.Connection conz = ConnectTools.connect(MainDatabase);
                java.sql.PreparedStatement pst = conz.prepareStatement(sqlDelete);
                pst.execute();
                JOptionPane.showMessageDialog(null,"Data Telah Dihapus");
            } catch (Exception e){JOptionPane.showMessageDialog(null,"Data Tidak Dapat Dihapus"+e.getMessage());}
        tampil_tabel_dbase();
        }else{
            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBatik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBatik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBatik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBatik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBatik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biaya_admin;
    private javax.swing.JTextField biaya_kirim;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hitung;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_saveedit;
    private javax.swing.JButton btn_simpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField harga_perkode;
    private javax.swing.JTextField harga_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah_kodi;
    private javax.swing.JComboBox kode_batik;
    private javax.swing.JTextField motif_batik;
    private javax.swing.JTextField nama_pembeli;
    private javax.swing.JTextField no_kirim;
    private javax.swing.JComboBox prs_persen;
    private javax.swing.JRadioButton prs_tidak;
    private javax.swing.JRadioButton prs_ya;
    private javax.swing.JTable tabel_form;
    private javax.swing.JTextField tanggal_kirim;
    private javax.swing.JTextField tarif_dua;
    private javax.swing.JTextField tarif_satu;
    private javax.swing.JTextField tarif_tiga;
    private javax.swing.JTextField total_biaya;
    // End of variables declaration//GEN-END:variables
}
